[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers =
    ui: Маркировка для UI тестов
    smoke: Маркировка для смоук тестов
    slow: Маркировка для медленных тестов
    regression: Маркировка для регресса
    critical: Маркировка для критичных тестов
    registration: Маркировка для регистрации
    authorization: Маркировка для авторизации